### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Welnnys** [MusilyApp/musily#2]
How do you add a song to a playlist, I have like 3 songs on my device ( mp3 as files ) and they are not showing anywhere in the app and I don't see a button to add them somehow. Also the app looks way different from the screenshots.

**Comment by FelipeYslaoker** [comment]
> How do you add a song to a playlist, I have like 3 songs on my device ( mp3 as files ) and they are not showing anywhere in the app and I don't see a button to add them somehow. Also the app looks way different from the screenshots.

1. Local Files Support:
At the moment, the app doesn't support local files, but I'm actively working on adding this feature. It will be available in a future update.


2. Adding to Favorites:
Currently, the only way to add a song to your favorites is by searching for it, or by navigating through albums or artists. Once you find the song, simply click the ❤️ button to add it to your favorites.


3. App Appearance:
The app should look exactly like the screenshots, with the only notable difference being the addition of a "Downloads" section in the bottom navigation.

Where did you download the app? For now, you can download the app from our official Telegram channel: https://t.me/MusilyApp. It will be available in other ways in the future.

**Comment by Welnnys** [comment]
I download it from your repository and for me it looks like this:
![image](https://github.com/user-attachments/assets/0365d699-faea-4525-af23-3343e9d7a3ff)

**Comment by Welnnys** [comment]
At first I thought that maybe I need to use the "Search" and it would search like thru youtube and else and download songs from there but it does not seem to be the case.

**Comment by Welnnys** [comment]
![image](https://github.com/user-attachments/assets/e43953c8-c54e-47d7-a44c-ad38378d4726)

Perhaps the "Search" is searching thru all downloaded songs on my phone?

**Comment by FelipeYslaoker** [comment]
> At first I thought that maybe I need to use the "Search" and it would search like thru youtube and else and download songs from there but it does not seem to be the case.

The app doesn't work in some countries due to an issue with the `dart_ytmusic_api` package. Unfortunately, I've tried fixing it without success so far. You can find more details about the package here:  
- [dart_ytmusic_api on pub.dev](https://pub.dev/packages/dart_ytmusic_api)  
- [GitHub repository](https://github.com/MusilyApp/dart_ytmusic_api)

The problem occurs during the first request, which should return the YouTube Music homepage. However, instead of the expected result, it consistently returns a "Your browser is deprecated" message, regardless of the user-agent string being used. Interestingly, the original TypeScript package (which I ported to Dart) works perfectly without this issue.

**Comment by Welnnys** [comment]
So basically the only way to get it to work is to change the package?

**Comment by FelipeYslaoker** [comment]
> So basically the only way to get it to work is to change the package?

Actually, I don't think there's another package available for YouTube Music. I need to identify the problem and solve it, or alternatively, create my own backend in TypeScript (which I'm currently considering).

**Comment by Welnnys** [comment]
Where in the app are u using dart_ytmusic_api, I went thru the entire pubspec.yaml and didn't fine it, nor anywhere in the code

**Comment by Welnnys** [comment]
Also maybe instead of youtube music you should use youtube itself because there are a lot of songs which are on there which are not on youtube music.

**Comment by FelipeYslaoker** [comment]
> Where in the app are u using dart_ytmusic_api, I went thru the entire pubspec.yaml and didn't fine it, nor anywhere in the code

Musily uses this repository https://github.com/MusilyApp/musily_repository

There's the location of dart_ytmusic_api

**Comment by FelipeYslaoker** [comment]
> Also maybe instead of youtube music you should use youtube itself because there are a lot of songs which are on there which are not on youtube music.

Yes, it's a good alternative. But the YouTube itself does not provide the Music database that makes my app look like Spotify. I'll find a solution, I don't know when, but I'll 🙏
